import {Cidade} from './cidade';

export const CIDADES : Cidade[] = 
	
[
 {"nomecidades":"ABREU E LIMA"}, 
 {"nomecidades":"AFOGADOS DA INGAZEIRA"}, 
 {"nomecidades":"AFRANIO"}, 
 {"nomecidades":"AGRESTINA"}, 
 {"nomecidades":"AGUA PRETA"}, 
 {"nomecidades":"AGUAS BELAS"}, 
 {"nomecidades":"ALAGOINHA"}, 
 {"nomecidades":"ALIANCA"}, 
 {"nomecidades":"ALTINHO"}, 
 {"nomecidades":"AMARAJI"}, 
 {"nomecidades":"ANGELIM"}, 
 {"nomecidades":"ARACOIABA"}, 
 {"nomecidades":"ARARIPINA"}, 
 {"nomecidades":"ARCOVERDE"}, 
 {"nomecidades":"BARRA DE GUABIRABA"}, 
 {"nomecidades":"BARREIROS"}, 
 {"nomecidades":"BELEM DE MARIA"}, 
 {"nomecidades":"BELEM DE SAO FRANCISCO"}, 
 {"nomecidades":"BELO JARDIM"}, 
 {"nomecidades":"BETANIA"}, 
 {"nomecidades":"BEZERROS"}, 
 {"nomecidades":"BODOCO"},
 {"nomecidades":"BOM CONSELHO"}, 
 {"nomecidades":"BOM JARDIM"}, 
 {"nomecidades":"BONITO"}, 
 {"nomecidades":"BREJAO"}, 
 {"nomecidades":"BREJINHO"}, 
 {"nomecidades":"BREJO DA MADRE DE DEUS"}, 
 {"nomecidades":"BUENOS AIRES"}, 
 {"nomecidades":"BUIQUE"}, 
 {"nomecidades":"CABO DE SANTO AGOSTINHO"}, 
 {"nomecidades":"CABROBO"}, 
 {"nomecidades":"CACHOEIRINHA"}, 
 {"nomecidades":"CAETES"}, 
 {"nomecidades":"CALCADO"}, 
 {"nomecidades":"CALUMBI"}, 
 {"nomecidades":"CAMARAGIBE"}, 
 {"nomecidades":"CAMOCIM DE SAO FELIX"}, 
 {"nomecidades":"CAMUTANGA"}, 
 {"nomecidades":"CANHOTINHO"}, 
 {"nomecidades":"CAPOEIRAS"}, 
 {"nomecidades":"CARNAUBA"}, 
 {"nomecidades":"CARNAUBEIRA DA PENHA"}, 
 {"nomecidades":"CARPINA"}, 
 {"nomecidades":"CARUARU"}, 
 {"nomecidades":"CASINHAS"}, 
 {"nomecidades":"CATENDE"}, 
 {"nomecidades":"CEDRO"}, 
 {"nomecidades":"CHA DE ALEGRIA"}, 
 {"nomecidades":"CHA GRANDE"}, 
 {"nomecidades":"CONDADO"}, 
 {"nomecidades":"CORRENTES"}, 
 {"nomecidades":"CORTES"}, 
 {"nomecidades":"CUMARU"}, 
 {"nomecidades":"CUPIRA"}, 
 {"nomecidades":"CUSTODIA"}, 
 {"nomecidades":"DORMENTES"}, 
 {"nomecidades":"ESCADA"}, 
 {"nomecidades":"EXU"}, 
 {"nomecidades":"FEIRA NOVA"}, 
 {"nomecidades":"FERNANDO DE NORONHA"}, 
 {"nomecidades":"FERREIROS"}, 
 {"nomecidades":"FLORES"}, 
 {"nomecidades":"FLORESTA"}, 
 {"nomecidades":"FREI MIGUELINHO"}, 
 {"nomecidades":"GAMELEIRA"}, 
 {"nomecidades":"GARANHUNS"}, 
 {"nomecidades":"GLORIA DO GOITA"}, 
 {"nomecidades":"GOIANA"}, 
 {"nomecidades":"GRANITO"}, 
 {"nomecidades":"GRAVATA"}, 
 {"nomecidades":"IATI"}, 
 {"nomecidades":"IBIMIRIM"}, 
 {"nomecidades":"IBIRAJUBA"}, 
 {"nomecidades":"IGARASSU"}, 
 {"nomecidades":"IGUARACY"}, 
 {"nomecidades":"INAJA"}, 
 {"nomecidades":"INGAZEIRA"}, 
 {"nomecidades":"IPOJUCA"}, 
 {"nomecidades":"IPUBI"}, 
 {"nomecidades":"ITACURUBA"}, 
 {"nomecidades":"ITAIBA"}, 
 {"nomecidades":"ITAMARACA"}, 
 {"nomecidades":"ITAMBE"}, 
 {"nomecidades":"ITAPETIM"}, 
 {"nomecidades":"ITAPISSUMA"}, 
 {"nomecidades":"ITAQUITINGA"}, 
 {"nomecidades":"JABOATAO DOS GUARARAPES"}, 
 {"nomecidades":"JAQUEIRA"}, 
 {"nomecidades":"JATAUBA"}, 
 {"nomecidades":"JATOBA"}, 
 {"nomecidades":"JOAO ALFREDO"}, 
 {"nomecidades":"JOAQUIM NABUCO"}, 
 {"nomecidades":"JUCATI"}, 
 {"nomecidades":"JUPI"}, 
 {"nomecidades":"JUREMA"}, 
 {"nomecidades":"LAGOA DO CARRO"}, 
 {"nomecidades":"LAGOA DO ITAENGA"}, 
 {"nomecidades":"LAGOA DO OURO"}, 
 {"nomecidades":"LAGOA DOS GATOS"}, 
 {"nomecidades":"LAGOA GRANDE"}, 
 {"nomecidades":"LAJEDO"},
 {"nomecidades":"LIMOEIRO"}, 
 {"nomecidades":"MACAPARANA"}, 
 {"nomecidades":"MACHADOS"}, 
 {"nomecidades":"MANARI"}, 
 {"nomecidades":"MARAIAL"}, 
 {"nomecidades":"MIRANDIBA"}, 
 {"nomecidades":"MOREILANDIA"}, 
 {"nomecidades":"MORENO"}, 
 {"nomecidades":"NAZARE DA MATA"}, 
 {"nomecidades":"OLINDA"},
 {"nomecidades":"OROBO"}, 
 {"nomecidades":"OROCO"}, 
 {"nomecidades":"OURICURI"}, 
 {"nomecidades":"PALMARES"}, 
 {"nomecidades":"PALMEIRINA"}, 
 {"nomecidades":"PANELAS"},
 {"nomecidades":"PARANATAMA"},
 {"nomecidades":"PARNAMIRIM"}, 
 {"nomecidades":"PASSIRA"}, 
 {"nomecidades":"PAUDALHO"}, 
 {"nomecidades":"PAULISTA"}, 
 {"nomecidades":"PEDRA"},
 {"nomecidades":"PESQUEIRA"}, 
 {"nomecidades":"PETROLANDIA"}, 
 {"nomecidades":"PETROLINA"}, 
 {"nomecidades":"POCAO"},
 {"nomecidades":"POMBOS"}, 
 {"nomecidades":"PRIMAVERA"},
 {"nomecidades":"QUIPAPA"}, 
 {"nomecidades":"QUIXABA"}, 
 {"nomecidades":"RECIFE"}, 
 {"nomecidades":"RIACHO DAS ALMAS"}, 
 {"nomecidades":"RIBEIRAO"}, 
 {"nomecidades":"RIO FORMOSO"}, 
 {"nomecidades":"SAIRE"}, 
 {"nomecidades":"SALGUEIRO"}, 
 {"nomecidades":"SALGADINHO"}, 
 {"nomecidades":"SALOA"}, 
 {"nomecidades":"SANHARO"}, 
 {"nomecidades":"SANTA CRUZ"}, 
 {"nomecidades":"SANTA CRUZ DA BAIXA VERDE"}, 
 {"nomecidades":"SANTA CRUZ DO CAPIBARIBE"}, 
 {"nomecidades":"SANTA FILOMENA"}, 
 {"nomecidades":"SANTA MARIA DA BOA VISTA"}, 
 {"nomecidades":"SANTA MARIA DO CAMBUCA"}, 
 {"nomecidades":"SANTA TERESINHA"}, 
 {"nomecidades":"SAO BENEDITO DO SUL"}, 
 {"nomecidades":"SAO BENTO DO UNA"}, 
 {"nomecidades":"SAO CAETANO"}, 
 {"nomecidades":"SAO JOAO"}, 
 {"nomecidades":"SAO JOAQUIM DO MONTE"}, 
 {"nomecidades":"SAO JOSE DA COROA GRANDE"}, 
 {"nomecidades":"SAO JOSE DO BELMONTE"}, 
 {"nomecidades":"SAO JOSE DO EGITO"}, 
 {"nomecidades":"SAO LOURENCO DA MATA"}, 
 {"nomecidades":"SAO VICENTE FERRER"}, 
 {"nomecidades":"SERRA TALHADA"}, 
 {"nomecidades":"SERRITA"}, 
 {"nomecidades":"SERTANIA"}, 
 {"nomecidades":"SIRINHAEM"}, 
 {"nomecidades":"SOLIDAO"}, 
 {"nomecidades":"SURUBIM"},
 {"nomecidades":"TABIRA"}, 
 {"nomecidades":"TACAIMBO"},
 {"nomecidades":"TACARATU"}, 
 {"nomecidades":"TAMANDARE"}, 
 {"nomecidades":"TAQUARITINGA DO NORTE"}, 
 {"nomecidades":"TEREZINHA"}, 
 {"nomecidades":"TERRA NOVA"}, 
 {"nomecidades":"TIMBAUBA"}, 
 {"nomecidades":"TORITAMA"}, 
 {"nomecidades":"TRACUNHAEM"}, 
 {"nomecidades":"TRINDADE"}, 
 {"nomecidades":"TRIUNFO"}, 
 {"nomecidades":"TUPANATINGA"}, 
 {"nomecidades":"TUPARETAMA"}, 
 {"nomecidades":"VENTUROSA"}, 
 {"nomecidades":"VERDEJANTE"}, 
 {"nomecidades":"VERTENTE DO LERIO"}, 
 {"nomecidades":"VERTENTES"}, 
 {"nomecidades":"VICENCIA"}, 
 {"nomecidades":"VITORIA DE SANTO ANTAO"}, 
 {"nomecidades":"XEXEU"}
]
